"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { BarChart3, Bookmark, Heart, Mail } from "lucide-react";
import { createClient, hasSupabaseConfig } from "@/lib/supabase/client";

export function LoginForm() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [googleBusy, setGoogleBusy] = useState(false); const router = useRouter();
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!hasSupabaseConfig()) return toast.error("Cinefolio needs its Supabase keys in .env.local before anyone can sign in."); setBusy(true); const { error } = await createClient().auth.signInWithPassword({ email, password }); if (error) toast.error(error.message); else { toast.success("The lights are down. Welcome back."); router.push("/"); router.refresh(); } setBusy(false); }
  async function signInWithGoogle() { if (!hasSupabaseConfig()) return toast.error("Cinefolio needs its Supabase keys in .env.local before anyone can sign in."); setGoogleBusy(true); const { error } = await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (error) { toast.error(error.message); setGoogleBusy(false); } }
  return <div className="login-content"><div className="login-kicker">Track <span>•</span> Remember <span>•</span> Relive</div><p className="eyebrow">More than a watchlist</p><h1>Your cinema journey, <em>forever.</em></h1><p className="login-intro">Keep every great film, your thoughts, and the memories that came with it—together in one personal archive.</p><div className="auth-card login-auth-card"><h2>Welcome to <span>Cinefolio</span></h2><p>Sign in to continue your movie journey.</p><button type="button" className="button button-dark w-full" onClick={signInWithGoogle} disabled={googleBusy}><GoogleIcon /> {googleBusy ? "Opening Google..." : "Continue with Google"}</button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit} className="space-y-4"><label className="label">Email address<input className="field mt-2" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label><label className="label">Password<input className="field mt-2" type="password" required value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="button button-accent mt-3 w-full" disabled={busy}><Mail size={18} />{busy ? "Opening your collection..." : "Sign in to Cinefolio"}</button></form></div><p className="login-signup">New here? <Link href="/signup">Create your free film history</Link></p><div className="login-benefits"><Benefit icon={<Bookmark />} title="Track" text="Log every watch" /><Benefit icon={<BarChart3 />} title="Discover" text="See your taste evolve" /><Benefit icon={<Heart />} title="Relive" text="Keep favourites close" /></div></div>;
}

function Benefit({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="login-benefit">{icon}<strong>{title}</strong><span>{text}</span></div>; }

function GoogleIcon() { return <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.27c0-.78-.07-1.53-.2-2.24H12v4.24h5.92a5.06 5.06 0 0 1-2.19 3.31v2.77h3.57c2.09-1.92 3.29-4.74 3.29-8.08Z" /><path fill="#34A853" d="M12 21.5c2.64 0 4.86-.87 6.48-2.36l-3.57-2.77c-.99.66-2.25 1.05-3.73 1.05-2.86 0-5.29-1.93-6.16-4.52H1.33v2.84A9.77 9.77 0 0 0 12 21.5Z" /><path fill="#FBBC05" d="M5.02 12.9A5.88 5.88 0 0 1 4.69 11c0-.66.12-1.3.33-1.9V6.26H1.33A9.5 9.5 0 0 0 1.33 15.74l3.69-2.84Z" /><path fill="#EA4335" d="M12 4.58c1.57 0 2.97.54 4.08 1.6l3.06-3.06C16.86.99 14.64 0 12 0A9.77 9.77 0 0 0 1.33 6.26l3.69 2.84C5.89 6.51 8.32 4.58 12 4.58Z" /></svg>; }
