"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Clapperboard } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function SignupPage() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [googleBusy, setGoogleBusy] = useState(false); const router = useRouter(); async function submit(event: React.FormEvent) { event.preventDefault(); if (!email.toLowerCase().endsWith("@gmail.com")) return toast.error("Cinefolio accounts use a Gmail address."); if (password.length < 6) return toast.error("Use at least six characters for your password."); setBusy(true); const { data, error } = await createClient().auth.signUp({ email, password }); if (error) toast.error(error.message); else if (data.session) { toast.success("Your film history starts now."); router.push("/movies"); } else toast.success("Check your Gmail inbox to get your ticket."); setBusy(false); } async function signUpWithGoogle() { setGoogleBusy(true); const { error } = await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (error) { toast.error(error.message); setGoogleBusy(false); } } return <main className="grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-8 flex items-center gap-2 text-[var(--accent-soft)]"><Clapperboard size={22} /><span className="font-bold">Cinefolio</span></div><p className="eyebrow">A place for the good ones</p><h1 className="mt-3 text-4xl font-semibold leading-tight">Keep the films worth talking about.</h1><div className="mt-8 border border-[var(--line)] bg-[var(--panel)] p-6 sm:p-8"><button type="button" className="button button-dark w-full" onClick={signUpWithGoogle} disabled={googleBusy}><GoogleIcon /> {googleBusy ? "Opening Google..." : "Continue with Google"}</button><div className="auth-divider"><span>or</span></div><form onSubmit={submit} className="space-y-4"><label className="label">Gmail address<input className="field mt-2" type="email" required pattern="[A-Za-z0-9._%+-]+@gmail\.com" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@gmail.com" /></label><label className="label">Password<input className="field mt-2" type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least six characters" /></label><button className="button button-accent mt-3 w-full" disabled={busy}>{busy ? "Setting up your collection..." : "Create my watch log"}</button></form><p className="mt-6 text-center text-sm text-[var(--muted)]">Already have an account? <Link className="text-[var(--accent-soft)]" href="/login">Sign in</Link></p></div></div></main>; }
function GoogleIcon() { return <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path fill="#EA4335" d="M12 10.2v3.9h5.5c-.24 1.4-1.7 4.1-5.5 4.1-3.3 0-6-2.7-6-6.2s2.7-6.2 6-6.2c1.9 0 3.2.8 3.9 1.5l2.7-2.6C16.9 3.1 14.7 2 12 2 6.9 2 2.7 6.2 2.7 12S6.9 22 12 22c6.9 0 9.3-4.9 9.3-7.4 0-.5 0-.9-.1-1.3H12Z"/></svg>; }