"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Clapperboard } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function SignupPage() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter(); async function submit(event: React.FormEvent) { event.preventDefault(); if (!email.toLowerCase().endsWith("@gmail.com")) return toast.error("Cinefolio accounts use a Gmail address."); if (password.length < 6) return toast.error("Use at least six characters for your password."); setBusy(true); const { data, error } = await createClient().auth.signUp({ email, password }); if (error) toast.error(error.message); else if (data.session) { toast.success("Your film history starts now."); router.push("/movies"); } else toast.success("Check your Gmail inbox to get your ticket."); setBusy(false); } return <main className="grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-8 flex items-center gap-2 text-[var(--accent-soft)]"><Clapperboard size={22} /><span className="font-bold">Cinefolio</span></div><p className="eyebrow">A place for the good ones</p><h1 className="mt-3 text-4xl font-semibold leading-tight">Keep the films worth talking about.</h1><div className="mt-8 border border-[var(--line)] bg-[var(--panel)] p-6 sm:p-8"><form onSubmit={submit} className="space-y-4"><label className="label">Gmail address<input className="field mt-2" type="email" required pattern="[A-Za-z0-9._%+-]+@gmail\.com" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@gmail.com" /></label><label className="label">Password<input className="field mt-2" type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least six characters" /></label><button className="button button-accent mt-3 w-full" disabled={busy}>{busy ? "Setting up your collection..." : "Create my watch log"}</button></form><p className="mt-6 text-center text-sm text-[var(--muted)]">Already have an account? <Link className="text-[var(--accent-soft)]" href="/login">Sign in</Link></p></div></div></main>; }
