import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Pencil, RotateCcw } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { RatingInput } from "@/components/RatingInput";
import { LogForm } from "@/components/LogForm";
import { createClient } from "@/lib/supabase/server";
import { formatDate } from "@/lib/utils";
import { DeleteLogButton } from "@/components/DeleteLogButton";
import type { MovieLog } from "@/lib/types";

export default async function MovieDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data } = await supabase.from("logs").select("*, movie:movies(*)").eq("id", id).single(); if (!data) notFound(); const log = data as MovieLog; const watchedDate = log.watched_date ?? log.watched_on; const review = log.review_text ?? log.review;
  return <AppShell><Link href="/movies" className="mb-8 inline-flex items-center gap-2 text-sm text-[var(--muted)] hover:text-[var(--paper)]"><ArrowLeft size={16} /> Back to your films</Link><div className="grid gap-8 lg:grid-cols-[280px_1fr]"><div className="poster-frame h-fit lg:sticky lg:top-24">{log.movie.poster_url ? <img src={log.movie.poster_url} alt={`${log.movie.title} poster`} /> : <div className="poster-placeholder">No poster yet</div>}</div><div><p className="eyebrow">A note from {formatDate(watchedDate)}</p><h1 className="mt-2 text-4xl font-semibold sm:text-6xl">{log.movie.title}</h1><p className="mt-3 text-[var(--muted)]">{[log.movie.release_year, log.movie.director && `Directed by ${log.movie.director}`, log.movie.runtime && `${log.movie.runtime} min`].filter(Boolean).join(" · ")}</p><div className="mt-6 flex items-center gap-4"><RatingInput value={log.rating} readOnly />{log.rewatch && <span className="tag"><RotateCcw size={13} className="mr-1" /> Rewatch</span>}</div><div className="mt-8 grid gap-3 border-y border-[var(--line)] py-5 text-sm sm:grid-cols-2"><Meta label="Country" value={log.movie.country} /><Meta label="Primary language" value={log.movie.language} /><Meta label="Audio languages" value={log.movie.audio_languages?.join(", ")} /><Meta label="Genres" value={log.movie.genre?.join(", ")} /></div>{log.movie.overview && <p className="mt-8 max-w-2xl leading-relaxed text-[var(--muted)]">{log.movie.overview}</p>}{review && <blockquote className="mt-10 border-l-2 border-[var(--accent)] pl-5 text-xl leading-relaxed text-[#ded4c8]">&ldquo;{review}&rdquo;</blockquote>}<div className="mt-8 flex flex-wrap gap-2">{log.tags.map((tag) => <Link className="tag transition hover:border-[var(--accent)] hover:text-[var(--paper)]" href={`/movies?tag=${encodeURIComponent(tag)}`} key={tag}>{tag}</Link>)}</div><details className="mt-12 border-t border-[var(--line)] pt-6"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-semibold"><Pencil size={15} className="text-[var(--accent)]" /> Edit this film note</summary><div className="mt-6 max-w-2xl"><LogForm logId={log.id} movieId={log.movie_id} existing={{ tmdb_id: String(log.movie.tmdb_id ?? ""), title: log.movie.title, release_year: String(log.movie.release_year ?? ""), director: log.movie.director ?? "", runtime: String(log.movie.runtime ?? ""), country: log.movie.country ?? "", language: log.movie.language ?? "", audio_languages: log.movie.audio_languages ?? [], genre: log.movie.genre ?? [], poster_url: log.movie.poster_url ?? "", backdrop_url: log.movie.backdrop_url ?? "", overview: log.movie.overview ?? "", original_language: log.movie.original_language ?? "", watched_on: watchedDate, rating: log.rating, review_text: review ?? "", tags: log.tags, rewatch: log.rewatch }} /></div></details><div className="mt-8 border-t border-[var(--line)] pt-5"><DeleteLogButton id={log.id} /></div></div></div></AppShell>;
}
function Meta({ label, value }: { label: string; value: string | number | null | undefined }) { return <div><p className="text-xs uppercase tracking-[.12em] text-[var(--muted)]">{label}</p><p className="mt-1 text-[var(--paper)]">{value || "Not recorded"}</p></div>; }
